//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vamosupcapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vamosupcEntities : DbContext
    {
        public vamosupcEntities()
            : base("name=vamosupcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<bus> buses { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<busByUser> busByUsers { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<busStop> busStops { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<busStopByRoute> busStopByRoutes { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<route> routes { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<routeByBu> routeByBus { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<user> users { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<userType> userTypes { get; set; }
    }
}
